name: Deploy Node App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - run: npm ci
      - run: npm run build  # if frontend

      - run: npm install -g pm2
      - run: npm install --save serve

      - run: |
          pm2 delete app || true
          pm2 start npm --name "app" -- run start